services:
  twgts:
    container_name: twgts
    restart: unless-stopped
    build:
      context: .
      network: host
    ports:
      - "9090:9090"
    volumes:
      - ~/Dropbox/.taskwarrior:/data/.task
